from assets.views.assets_views import AssetListCreateAPIView, AssetDetailsView, UserAssetDetailsView
from assets.views.assets_history_views import asset_history_list
from assets.views.employee_views import employee_list, EmployeeListCreateAPIView