from assets.views.assets_views import AssetListCreateAPIView, AssetDetailsView, UserAssetDetailsView
from assets.views.assets_history_views import AssetHistoryListAPIView
from assets.views.employee_views import employee_list, EmployeeListCreateAPIView, EmployeeDetailsView, EmployeeSideDetailsUpdate
