# Generated by Django 5.2.4 on 2025-08-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="full_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
