# Generated by Django 5.2.4 on 2025-08-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='full_name',
        ),
    ]
