# Generated by Django 5.2.4 on 2025-08-20 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_alter_employeeprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assethistory",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="assets.asset",
            ),
        ),
    ]
