# Generated by Django 5.2.4 on 2025-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_alter_assethistory_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
