# Generated by Django 5.2.4 on 2025-08-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_employeeprofile_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="avatar_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
