# Generated by Django 5.2.4 on 2025-08-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_alter_employeeprofile_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.department",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
