# Generated by Django 5.2.4 on 2025-08-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0012_alter_employeeprofile_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="is_verified",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
