# Generated by Django 5.2.4 on 2025-08-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_employeeprofile_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
