name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # Install ruff and black first, then your project dependencies
          pip install ruff==0.0.272 black==25.1.0
          pip install -r requirements.txt

      - name: Run Ruff checks
        run: |
          ruff .
          

      - name: Run Black checks
        run: |
          black --check .